import { readFileSync } from "node:fs";
const base = JSON.parse(
  readFileSync(new URL("./stryker.config.json", import.meta.url), "utf8"),
);
// Explicit critical-guard scope; not whole-module mutation coverage.
const guards = [
  [
    "src/server/authored-oauth.ts",
    "const supported = discovery.dpopSigningAlgorithms",
    3,
  ],
  [
    "src/server/authored-oauth.ts",
    "dpop_bound_access_tokens: input.dpopRequired",
    0,
  ],
  ["src/server/authored-oauth.ts", "const dpopJwk = useDpop", 2],
  [
    "src/server/authored-app.ts",
    "if (registered.dpopRequired && !dpop) return;",
    2,
  ],
  [
    "src/server/authored-operations.ts",
    'if (discovery.dpopRequired && token.token_type?.toLowerCase() !== "dpop")',
    1,
  ],
  [
    "src/server/authored-operations.ts",
    "async function discardRejectedRegistration(",
    14,
  ],
  [
    "src/server/authored-operations.ts",
    '["username-in-use", "email-in-use"].includes(result.reason)',
    0,
    2,
  ],
  [
    "src/server/authored-oauth.ts",
    "input.discovery.requirePushedAuthorizationRequests &&",
    1,
  ],
  [
    "src/server/authored-oauth.ts",
    "if (input.discovery.requirePushedAuthorizationRequests) throw error;",
    0,
  ],
  ["src/server/authored-operations.ts", "      ...boundDiscovery,", 0],
  ["src/server/teaching-runtime.ts", "options.authoringFetch ??", 0],
  ["src/server/github-runtime.ts", "options.authoredFetch ??", 0],
  [
    "src/server/authored-operations.ts",
    "parsed.data.subject !== context.actor.subjectId ||",
    7,
  ],
  [
    "src/server/authored-operations.ts",
    "if (started.expires <= Date.now())",
    1,
  ],
  ["src/server/authored-human.ts", "prior.value.isolated ||", 0],
  ["src/server/browser-executor.ts", "async function openBrowser(", 44],
  ["src/server/browser-executor.ts", 'serviceWorkers: "block",', 0],
  [
    "src/server/browser-executor.ts",
    "request.frameId === frameTree.frame.id &&",
    6,
  ],
  ["src/server/browser-executor.ts", 'await session.send("Fetch.enable", {', 2],
  [
    "src/server/browser-executor.ts",
    "(!frame || (!frame.parentFrame() && frame.page() !== page))",
    0,
  ],
  ["src/server/browser-executor.ts", "popupBlocked = true;", 0, 3],
  ["src/server/browser-executor.ts", "if (!targetInfo.browserContextId)", 0],
  ["src/server/browser-executor.ts", 'target.type === "page" &&', 2],
  ["src/server/browser-executor.ts", 'await session.send("Page.enable");', 0],
  ["src/server/browser-executor.ts", "recordSession: false", 2],
  ["src/server/browser-executor.ts", "          privateValues.add(value);", 0],
  ["src/server/browser-executor.ts", "if (await focusRequiredInput(page))", 1],
  ["src/server/browser-executor.ts", 'if (role === "birth-date")', 4],
  ["src/server/browser-executor.ts", "function rememberPrivateLink(", 19],
  ["src/server/browser-executor.ts", "if (failure) return failure;", 0, 2],
  ["src/server/browser-executor.ts", "if (outcome) return outcome;", 0],
  ["src/server/browser-executor.ts", "if (completed) return completed;", 0],
  ["src/server/browser-executor.ts", "if (result) return result;", 0, 3],
  ["src/server/browser-executor.ts", "if (!inspected) {", 0],
  [
    "src/server/browser-executor.ts",
    "for (let step = 0; step < 24 && Date.now() < deadline; step += 1)",
    0,
  ],
  ["src/server/browser-executor.ts", "if (!(await target.isChecked()))", 3],
  ["src/server/browser-executor.ts", "const body = request.postData();", 44],
  ["src/server/browser-executor.ts", "let submissionUncertain = false;", 0],
  ["src/server/browser-executor.ts", "!submissionUncertain &&", 0],
  ["src/server/browser-executor.ts", "else if (submissionUncertain)", 1],
  ["src/server/browser-executor.ts", '? "submission-uncertain"', 0, 2],
  [
    "src/server/authored-operations.ts",
    "if (!response || response.status === 429 || response.status >= 500)",
    1,
  ],
  [
    "src/server/authored-operations.ts",
    'token.token_type?.toLowerCase() === "dpop"',
    2,
  ],
  [
    "src/server/authored-operations.ts",
    "const identity = await saveAuthoredGrantSession(",
    10,
  ],
  ["src/server/authored-operations.ts", "return saveAuthoredGrantSession(", 10],
  [
    "src/server/authored-operations.ts",
    "...(json.data.email_verified === true &&",
    1,
  ],
  [
    "src/server/authored-operations.ts",
    "? stored.verifiedEmail !== intent.identifier",
    0,
  ],
  ["src/server/authored-operations.ts", "(session.data.verifiedEmail &&", 1],
  [
    "src/server/authored-human.ts",
    "ticket.subject === context.actor.subjectId &&",
    3,
  ],
  [
    "src/server/authored-human.ts",
    "!ticketMatchesAttempt(prior.value, context, pending.node.id) ||",
    0,
    2,
  ],
  ["src/server/authored-human.ts", "const nextInterval = Math.max(", 3],
  [
    "src/server/authored-human.ts",
    "if ((prior.value.nextPoll ?? 0) > Date.now())",
    0,
  ],
  [
    "src/server/authored-human.ts",
    "nextPoll: Date.now() + nextInterval * 1000,",
    0,
  ],
  ["src/server/hosted/http.ts", 'if (path.startsWith("/api/v1/teaching/"))', 1],
  [
    "src/server/authored-operations.ts",
    '          selected === "device" ||',
    0,
  ],
  [
    "src/server/authored-human.ts",
    "((await readAuthoredCeremony(store, context.actor, context.runId)) ===",
    3,
  ],
  ["src/react/teaching.tsx", "  async function teach(", 41],
  ["src/react/teaching.tsx", "function ConnectionStatus(", 177],
  ["src/react/teaching.tsx", "  const authoredWaiting =", 9],
  ["src/react/teaching.tsx", "if (currentRun.current !== run) return;", 0, 2],
  ["src/react/teaching.tsx", "currentRun.current !== initialRun ||", 0],
  [
    "src/react/teaching.tsx",
    "if (!abort.signal.aborted && currentRun.current === initialRun)",
    0,
  ],
  [
    "src/server/authored-human.ts",
    "  const interactWithBrowser = async (form: URLSearchParams) => {",
    20,
  ],
  [
    "src/server/authored-human.ts",
    'if (form.get("action") === "browser") return interactWithBrowser(form);',
    0,
  ],
  [
    "src/server/jira-human.ts",
    'if (request.method === "POST") return submitHumanInput();',
    1,
  ],
  [
    "src/server/supabase-human.ts",
    'if (request.method === "POST") return submitHumanInput();',
    1,
  ],
  [
    "src/server/authored-operations.ts",
    "export function accountMatchesIntent(",
    8,
  ],
  [
    "src/server/github-runtime.ts",
    "        decodeURIComponent(callbackUrl.pathname) ===",
    20,
  ],
  ["src/server/teaching-http.ts", 'action !== "account" &&', 0],
  ["src/server/teaching-http.ts", "const humanResponse = await humanHttp", 2],
  ["src/server/teaching-http.ts", 'if (path.startsWith("/authoring/"))', 1],
  ["src/server/teaching-http.ts", 'if (path.startsWith("/tools/"))', 1],
  ["src/server/teaching-http.ts", 'if (path === "/runs" ||', 1],
  ["src/server/teaching-http.ts", 'if (path === "/demonstrations" ||', 1],
  ["src/server/teaching-http.ts", 'if (path.startsWith("/drafts/"))', 1],
  ["src/server/teaching-http.ts", 'path === "/recipes" ||', 3],
  ["src/server/teaching-http.ts", 'if (path.startsWith("/agent/"))', 1],
  ["src/server/teaching-http.ts", "function errorResponse(", 24],
];
export default {
  ...base,
  concurrency: 1,
  mutate: [
    ...guards.flatMap(([file, marker, lines, expected = 1]) => {
      const source = readFileSync(file, "utf8").split("\n");
      const matches = source.flatMap((line, index) =>
        line.includes(marker) ? [index + 1] : [],
      );
      if (matches.length !== expected)
        throw new Error(`Auth guard count changed: ${file} ${marker}`);
      return matches.map((line) => `${file}:${line}-${line + lines}`);
    }),
    "src/server/authored-account.ts",
    "src/server/public-auth-fetch.ts",
    "src/server/browser-egress.ts",
  ],
  tap: {
    ...base.tap,
    testFiles: [
      "tests/browser-terminal.test.ts",
      "tests/browser-executor.test.ts",
      "tests/auth-runtime-discovery.test.ts",
      "tests/authoring-tools.test.ts",
      "tests/authored-oauth.test.ts",
      "tests/authored-app.test.ts",
      "tests/public-auth-fetch.test.ts",
      "tests/browser-egress.test.ts",
      "tests/provider-discovery.test.ts",
      "tests/authored-browser-resume.test.ts",
      "tests/authored-account-claim.test.ts",
      "tests/hosted-http.test.ts",
      "tests/teaching-component.test.ts",
      "tests/teaching-routing.test.ts",
      "tests/jira-children.test.ts",
      "tests/supabase-runtime.test.ts",
      "tests/contracts/protocol.test.ts",
      "tests/chaos.test.ts",
    ],
  },
  jsonReporter: { fileName: "artifacts/auth-mutation/mutation.json" },
  htmlReporter: { fileName: "artifacts/auth-mutation/index.html" },
};
